project: 
  type: website
  output-dir: docs
  render:     
    - "*.qmd"
    - "!slides/"

execute:
  freeze: auto

website:
  page-navigation: true  
  title: "PSAW 2025 Quarto Workshop"
  favicon: "images/favicon-16x16.png"
  site-url: https://nmfs-opensci.github.io/PSAW2025-Quarto-Workshop/
  repo-url: https://github.com/nmfs-opensci/PSAW2025-Quarto-Workshop
  repo-actions: [edit, issue, source]
  
  page-footer: <img src="https://github.com/nmfs-opensci/assets/blob/main/logo/nmfs-opensci-logo2.png?raw=true" alt="NMFS Open Science logo" style="width:150px"><br />NMFS Open Science (2023)

  navbar:
    background: primary
    search: true
    right: 
      - icon: server
        href: https://workshop.nmfs-openscapes.2i2c.cloud/
        text: "JupyterHub"
      - icon: github
        href: https://github.com/nmfs-opensci/PSAW-2025-Quarto-Workshop
        text: "repo"
      - icon: globe
        href: https://github.com/nmfs-opensci
        text: "GH org"
  sidebar:
    logo: https://github.com/nmfs-opensci/assets/blob/main/logo/nmfs-opensci-logo2.png?raw=true
    pinned: true
    align: center
    
    style: "docked"
    collapse-level: 1
    toc-expand: false
    contents:
      - section: "Welcome"
        href: index.qmd
      - section: "Getting Started"
      - section: "Tutorials"
        contents:
          - content/intro.qmd
          - content/quarto_markdown.qmd
          - content/dynamic_content.qmd
          - content/projects_formats.qmd
      # - href: content/resources.qmd
      - text: "Resources: Coming soon!"
      - text: <img width=100px>
      - text: <img width=100px>
      - text: <img src="/images/noaa_emblem_logo-2022.png" width=100px>
        href: https://fisheries.noaa.gov
format:
  html:
    theme:
      light: brand
      dark: [cosmo, theme-dark.scss]
    code-background: true
    code-copy: true
    css: styles.css
    toc: true
    toc-depth: 2
    include-before-body: translate.html

#filters:
#  - include-files.lua
#  - quarto
