---
title: Schedule
---

All times Pacific. Note material marked \* is NOAA access restricted.

+--------------------------------+-------------------------------------------------------------------------------------------------------------+---------------------------+---------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------+
| Topic                          | Description                                                                                                 | Material                  | Meeting Links                                     | Recordings                                                                                                                    |
+================================+=============================================================================================================+===========================+===================================================+===============================================================================================================================+
| Introduction to Git and GitHub | Basics of git commands, repository management, project management, and collaboration using GitHub           | [Link](content/intro.qmd) | [Mon 4/7](https://meet.google.com/wmf-zter-bus)   | Monday 4/7 (not available; issue with recording)                                                                              |
|                                |                                                                                                             |                           |                                                   |                                                                                                                               |
|                                |                                                                                                             |                           | [Tues 4/8](https://meet.google.com/inx-nyrj-hmk)  | [Tuesday 4/8 (Incomplete recording)\*](https://drive.google.com/file/d/1rjvIRgexOe2D2l5fFf9GhXsQncWX6UYK/view?usp=drive_link) |
|                                |                                                                                                             |                           |                                                   |                                                                                                                               |
|                                |                                                                                                             |                           | [Mon 4/14](https://meet.google.com/wmf-zter-bus)  | [Monday 4/14\*](https://drive.google.com/file/d/1QZc8ixRZyUKyZoTyb_ERk7PeHWbi85aF/view?usp=sharing)                           |
|                                |                                                                                                             |                           |                                                   |                                                                                                                               |
|                                |                                                                                                             |                           | [Tues 4/15](https://meet.google.com/inx-nyrj-hmk) | [Tuesday, 4/15\*](https://drive.google.com/file/d/1goH2jSuRZ17U1kCRe79M_LaQpWNDMtE4/view?usp=sharing)                         |
|                                |                                                                                                             |                           |                                                   |                                                                                                                               |
|                                |                                                                                                             |                           | [Mon 4/21](https://meet.google.com/wmf-zter-bus)  | [Monday, 4/21\*](https://drive.google.com/file/d/1-JuvFqiaDgLKB6sY_6AAgZC29dzwxI94/view?usp=drive_link)                       |
|                                |                                                                                                             |                           |                                                   |                                                                                                                               |
|                                |                                                                                                             |                           | [Tues 4/22](https://meet.google.com/inx-nyrj-hmk) | [Tuesday, 4/22\*](https://drive.google.com/file/d/18iDAN_KNsGyS5YJH2std6uh3-5poRCGF/view?usp=sharing)                         |
+--------------------------------+-------------------------------------------------------------------------------------------------------------+---------------------------+---------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------+
| Markdown and README files      | Become familiar with markdown formatting for README files, issues, Pull Requests, and discussions on GitHub | TBD                       | [Thurs 5/29](meet.google.com/ovn-apnj-yut)        |                                                                                                                               |
|                                |                                                                                                             |                           |                                                   |                                                                                                                               |
|                                |                                                                                                             |                           | [Tues 6/3](meet.google.com/ovn-apnj-yut)          |                                                                                                                               |
+--------------------------------+-------------------------------------------------------------------------------------------------------------+---------------------------+---------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------+
| GitHub Pages                   | How to make a website from a GitHub repository using GitHub Pages                                           | TBD                       | [Thurs 6/12](meet.google.com/ovn-apnj-yut)        |                                                                                                                               |
|                                |                                                                                                             |                           |                                                   |                                                                                                                               |
|                                |                                                                                                             |                           | [Tues 6/17](meet.google.com/ovn-apnj-yut)         |                                                                                                                               |
+--------------------------------+-------------------------------------------------------------------------------------------------------------+---------------------------+---------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------+
| Forks                          | Forking a repository, how to work with forks, and why we use them                                           | TBD                       | [Thurs 6/26](meet.google.com/ovn-apnj-yut)        |                                                                                                                               |
|                                |                                                                                                             |                           |                                                   |                                                                                                                               |
|                                |                                                                                                             |                           | [Tues 7/1](meet.google.com/ovn-apnj-yut)          |                                                                                                                               |
+--------------------------------+-------------------------------------------------------------------------------------------------------------+---------------------------+---------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------+
| Branches and Pull Requests     | Creating a branch, why to use branches, and using pull request to merge changes from branches               | TBD                       | [Thurs 7/10](meet.google.com/ovn-apnj-yut)        |                                                                                                                               |
|                                |                                                                                                             |                           |                                                   |                                                                                                                               |
|                                |                                                                                                             |                           | [Tues 7/15](meet.google.com/ovn-apnj-yut)         |                                                                                                                               |
+--------------------------------+-------------------------------------------------------------------------------------------------------------+---------------------------+---------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------+
| Git Workflows                  | Using branches to organize and develop workflows in GitHub                                                  | TBD                       | [Thurs 8/7](meet.google.com/ovn-apnj-yut)         |                                                                                                                               |
|                                |                                                                                                             |                           |                                                   |                                                                                                                               |
|                                |                                                                                                             |                           | [Tues 8/12](meet.google.com/ovn-apnj-yut)         |                                                                                                                               |
+--------------------------------+-------------------------------------------------------------------------------------------------------------+---------------------------+---------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------+
| Merge Conflicts                | Why merge conflicts occur, how to address them, and best practices to avoid them in the first place         | TBD                       | [Thurs 7/17](meet.google.com/ovn-apnj-yut)        |                                                                                                                               |
|                                |                                                                                                             |                           |                                                   |                                                                                                                               |
|                                |                                                                                                             |                           | [Tues 7/29](meet.google.com/ovn-apnj-yut)         |                                                                                                                               |
+--------------------------------+-------------------------------------------------------------------------------------------------------------+---------------------------+---------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------+
| Issues                         | Types of issues, assigning issues, and using issue templates                                                | TBD                       | [Thurs 8/21](meet.google.com/ovn-apnj-yut)        |                                                                                                                               |
|                                |                                                                                                             |                           |                                                   |                                                                                                                               |
|                                |                                                                                                             |                           | [Tues 8/26](meet.google.com/ovn-apnj-yut)         |                                                                                                                               |
+--------------------------------+-------------------------------------------------------------------------------------------------------------+---------------------------+---------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------+
| Project Management             | Using GitHub Issues and Projects for project management                                                     | TBD                       | [Thurs 9/4](meet.google.com/ovn-apnj-yut)         |                                                                                                                               |
|                                |                                                                                                             |                           |                                                   |                                                                                                                               |
|                                |                                                                                                             |                           | [Tues 9/9](meet.google.com/ovn-apnj-yut)          |                                                                                                                               |
+--------------------------------+-------------------------------------------------------------------------------------------------------------+---------------------------+---------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------+
| Advanced Git                   | Git on the command line, advanced features and functions                                                    | TBD                       | [Thurs 9/18](meet.google.com/ovn-apnj-yut)        |                                                                                                                               |
|                                |                                                                                                             |                           |                                                   |                                                                                                                               |
|                                |                                                                                                             |                           | [Tues 9/23](meet.google.com/ovn-apnj-yut)         |                                                                                                                               |
+--------------------------------+-------------------------------------------------------------------------------------------------------------+---------------------------+---------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------+
| GitHub Actions                 | Automating tasks and workflows using GitHub Actions                                                         | TBD                       | [Thurs 10/1](meet.google.com/ovn-apnj-yut)        |                                                                                                                               |
|                                |                                                                                                             |                           |                                                   |                                                                                                                               |
|                                |                                                                                                             |                           | [Tues 10/6](meet.google.com/ovn-apnj-yut)         |                                                                                                                               |
+--------------------------------+-------------------------------------------------------------------------------------------------------------+---------------------------+---------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------+