---
title: GitHub Workshop for CB Genetics and Evolution Program
date: '2025-03-05'
---

GitHub is an important platform for many NOAA Fisheries staff and teams to share and collaborate. In 2023, an Authorization To Use for GitHub Enterprise Cloud was signed, which provides a secure, private, access-controlled and managed platform for staff. In 2024, the GitHub Governance Team (GGT) provided a series of workshops to onboard NOAA Fisheries scientists to GitHub Enterprise and provide training in the use of Git and GitHub for NOAA Fisheries. In 2025, NMFS Open Science will be leading a second iteration of these workshops to provide NOAA Fisheries staff with the necessary skills to effectively incorporate Git and GitHub into existing workflows.

The GGT has outlined several use cases for why you may want to incorporate Git and GitHub into your workflows:

- Development and distribution of scientific products and fundamental research communications.
- Development of software and statistical packages for data analysis, e.g. stock assessment models.
- Project/team management using GitHub project boards, issue tracking, task tracking.
- Collaborative development of reports that combine data, resource intensive analysis, and text.
- Automated report generation (using connection to online database and continuous integration).
- Educational resources and learning activities.

## Aims and Objectives
This sessions will use a mixture of directed, interactive lessons and GitHub Skills to provide NOAA Fisheries staff within the Conservation Biology Genetics and Evolution Program with the knowledge required for basic repository management using Git commands, collaboration, and project management, as well as dedicated time to put these skills to use in setting up an existing project or workflow with Git and GitHub.

## Agenda

-   10:00-10:10 [Why Git/GitHub?]
-   10:10-10:20 [GitHub Enterprise]
-   10:20-10:50 [Introduction to GitHub - Tutorial]
-   10:50-11:30 [Pull Requests and Collaboration - Tutorial]
-   11:30-11:45 Break
-   11:45-12:15 [Project Management]
-   12:15-13:00 [Putting Everything Together]

## Why Git/GitHub?

<iframe class="slide-deck" src="why_git.html" width="900" height="600">

</iframe>

## GitHub Enterprise

<iframe class="slide-deck" src="ghec.html" width="900" height="600">

</iframe>

## Introduction to GitHub - Tutorial

[GitHub Skills - Introduction to GitHub](https://github.com/skills/introduction-to-github)

## Pull Requests and Collaboration - Tutorial

[GitHub Skills - Review Pull Requests](https://github.com/skills/review-pull-requests)

[GitHub Skills - Resolve Merge Conflicts](https://github.com/skills/resolve-merge-conflicts)

## Project Management

<iframe class="slide-deck" src="project_management.html" width="900" height="600">

</iframe>

## Putting Everything Together

<iframe class="slide-deck" src="guided_exercise.html" width="900" height="600">

</iframe>
