---
title: "Intro to GitHub Enterprise"
subtitle: "...and how it is and isn't different"
author: "Eli Holmes"
format: 
    revealjs:
        
        controls: true
---

## What is GitHub Enterprise?

-   An account with GitHub organizations (orgs) that has more controls than GitHub Free.

-   Your personal GitHub account can have repos in GitHub Free orgs or GitHub Enterprise orgs.

-   Your identity (username) does not change -- as long as your user account uses your noaa.gov email.

## How is GitHub Enterprise different?

-   It is controlled by work and has more rules

-   It requires CAC sign-in - more secure

-   It requires a license.

-   Outside (non NOAA) collaborators have to be added by an admin to repos. They use a license if the repo is private or internal

## How is GitHub Enterprise different?

-   GitHub 3rd party applications require approval

-   It has more features: private and internal GitHub Pages, more GitHub Action minutes, bigger files allowed.

-   Allows internal repositories only visible to NMFS GitHub users across GHEC. See code from other science centers (if they made it internal)

-   Collaborate on repos with any other NMFS GHEC org. You can be on orgs at other centers

## How is GitHub Enterprise different?

-   Has IT managed automatic backups.

-   NMFS doesn't lose code due to repo owner leaving NOAA

-   FedRAMP approved unlike GitHub free

## How is GitHub Enterprise not different?

-   You can create repos just like in GitHub Free

-   You have access to the usual collaboration tools: projects, GitHub Actions, GitHub Pages

-   You are admin on your own repos and can admin them as usual...except re outside collaborators.