---
title: Schedule
---

Introductory workshops were held Mondays at 10am PT/1pm ET and Tuesdays at 1pm PT/4pm ET for 3 weeks starting April 7th.

Single-topic sessions are being held Thursdays at 12:30pm PT/3:30pm ET and Tuesdays at 11:00am PT/2:00pm ET, with topics switching every two weeks starting May 29th.

See the [Open Science Calendar](https://calendar.google.com/calendar/u/0?cid=Y185MTZiNjk0OGVmMmVlOGI3ZDQ5YzI4NjYxZWZjMDc5ODMwM2MyNzQyYmUzOTljOTI5MGZhMDJkOTMyMGM3NjllQGdyb3VwLmNhbGVuZGFyLmdvb2dsZS5jb20) for meeting links. Note that recordings and calendar links are restricted to NOAA employees and affiliates.

+--------------------------------+-------------------------------------------------------------------------------------------------------------+---------------------------------------------+------------+-----------------------------------------------------------------------------------------------------------------------------+
| Topic                          | Description                                                                                                 | Material                                    | Dates      | Recordings                                                                                                                  |
+================================+=============================================================================================================+=============================================+============+=============================================================================================================================+
| Introduction to Git and GitHub | Basics of git commands, repository management, project management, and collaboration using GitHub           | [Link](intro/intro.qmd)                     | Mon 4/7    | Monday 4/7 (not available; issue with recording)                                                                            |
|                                |                                                                                                             |                                             |            |                                                                                                                             |
|                                |                                                                                                             |                                             | Tues 4/8   | [Tuesday 4/8 (Incomplete recording)](https://drive.google.com/file/d/1rjvIRgexOe2D2l5fFf9GhXsQncWX6UYK/view?usp=drive_link) |
|                                |                                                                                                             |                                             |            |                                                                                                                             |
|                                |                                                                                                             |                                             | Mon 4/14   | [Monday 4/14](https://drive.google.com/file/d/1QZc8ixRZyUKyZoTyb_ERk7PeHWbi85aF/view?usp=sharing)                           |
|                                |                                                                                                             |                                             |            |                                                                                                                             |
|                                |                                                                                                             |                                             | Tues 4/15  | [Tuesday, 4/15](https://drive.google.com/file/d/1goH2jSuRZ17U1kCRe79M_LaQpWNDMtE4/view?usp=sharing)                         |
|                                |                                                                                                             |                                             |            |                                                                                                                             |
|                                |                                                                                                             |                                             | Mon 4/21   | [Monday, 4/21](https://drive.google.com/file/d/1-JuvFqiaDgLKB6sY_6AAgZC29dzwxI94/view?usp=drive_link)                       |
|                                |                                                                                                             |                                             |            |                                                                                                                             |
|                                |                                                                                                             |                                             | Tues 4/22  | [Tuesday, 4/22](https://drive.google.com/file/d/18iDAN_KNsGyS5YJH2std6uh3-5poRCGF/view?usp=sharing)                         |
+--------------------------------+-------------------------------------------------------------------------------------------------------------+---------------------------------------------+------------+-----------------------------------------------------------------------------------------------------------------------------+
| Markdown and README files      | Become familiar with markdown formatting for README files, issues, Pull Requests, and discussions on GitHub | [Link](markdown/markdown.qmd)               | Thurs 5/29 | [Thurs 5/29](https://drive.google.com/file/d/1OC1kFU4mzVgWsBLFY5Ft6rWW6518zlax/view?usp=sharing)                            |
|                                |                                                                                                             |                                             |            |                                                                                                                             |
|                                |                                                                                                             |                                             | Tues 6/3   | [Tues 6/3 (audio degradation issues)](https://drive.google.com/file/d/1hy-ztB-uujfK1-9_JQDJ7-qt-pbtBpK0/view?usp=sharing)   |
+--------------------------------+-------------------------------------------------------------------------------------------------------------+---------------------------------------------+------------+-----------------------------------------------------------------------------------------------------------------------------+
| GitHub Pages                   | How to make a website from a GitHub repository using GitHub Pages                                           | [Link](github-pages/github-pages.qmd)       | Thurs 6/12 | Thurs 6/12 (not available; canceled session)                                                                                |
|                                |                                                                                                             |                                             |            |                                                                                                                             |
|                                |                                                                                                             |                                             | Tues 6/17  | [Tues 6/17](https://drive.google.com/file/d/1hDRPGPLQb9lSEDB8ORs44HzZBIl3XcGQ/view?usp=sharing)                             |
+--------------------------------+-------------------------------------------------------------------------------------------------------------+---------------------------------------------+------------+-----------------------------------------------------------------------------------------------------------------------------+
| Forks                          | Forking a repository, how to work with forks, and why we use them                                           | [Link](forking/forking.qmd)                 | Thurs 6/26 | [Thurs 6/26](https://drive.google.com/file/d/1KgOj8W6XwZ8Y9LyPjMkgLFmGcSTXtMC9/view?usp=sharing)                            |
|                                |                                                                                                             |                                             |            |                                                                                                                             |
|                                |                                                                                                             |                                             | Tues 7/1   | [Tues 7/1](https://drive.google.com/file/d/1HgGkgK-M-LVv9NPqzCdzkrhhZwXlhGFz/view?usp=sharing)                              |
+--------------------------------+-------------------------------------------------------------------------------------------------------------+---------------------------------------------+------------+-----------------------------------------------------------------------------------------------------------------------------+
| Branches and Pull Requests     | Creating a branch, why to use branches, and using pull request to merge changes from branches               | [Link](branches/branches.qmd)               | Thurs 7/10 | [Thurs 7/10](https://drive.google.com/file/d/1F7h77D3Ay2caiiZfoXRnLuDeJOlmoqos/view?usp=sharing)                            |
|                                |                                                                                                             |                                             |            |                                                                                                                             |
|                                |                                                                                                             |                                             | Tues 7/15  | Tues 7/15 (not available; technical difficulties)                                                                           |
+--------------------------------+-------------------------------------------------------------------------------------------------------------+---------------------------------------------+------------+-----------------------------------------------------------------------------------------------------------------------------+
| Git Workflows                  | Using branches to organize and develop workflows in GitHub                                                  | [Link](workflows/workflows.qmd)             | Thurs 7/24 | [Thurs 7/24](https://drive.google.com/file/d/1RZoqdNiCTOREArU_t38Q0ZIx1J-FhF5e/view?usp=sharing)                            |
|                                |                                                                                                             |                                             |            |                                                                                                                             |
|                                |                                                                                                             |                                             | Tues 7/29  | [Tues 7/29](https://drive.google.com/file/d/10rDJj9UBcXV5hX-Ozy1notBElvLRZucX/view?usp=sharing)                             |
+--------------------------------+-------------------------------------------------------------------------------------------------------------+---------------------------------------------+------------+-----------------------------------------------------------------------------------------------------------------------------+
| Merge Conflicts                | Why merge conflicts occur, how to address them, and best practices to avoid them in the first place         | [Link](merge-conflicts/merge-conflicts.qmd) | Thurs 8/7  | [Thurs 8/7](https://drive.google.com/file/d/14MxwT_XLbIfFGhLrkT3MhoLOyXtgMcuk/view?usp=sharing)                             |
|                                |                                                                                                             |                                             |            |                                                                                                                             |
|                                |                                                                                                             |                                             | Tues 8/12  |                                                                                                                             |
+--------------------------------+-------------------------------------------------------------------------------------------------------------+---------------------------------------------+------------+-----------------------------------------------------------------------------------------------------------------------------+
| Issues                         | Types of issues, assigning issues, and using issue templates                                                | TBD                                         | Thurs 8/21 |                                                                                                                             |
|                                |                                                                                                             |                                             |            |                                                                                                                             |
|                                |                                                                                                             |                                             | Tues 8/26  |                                                                                                                             |
+--------------------------------+-------------------------------------------------------------------------------------------------------------+---------------------------------------------+------------+-----------------------------------------------------------------------------------------------------------------------------+
| Project Management             | Using GitHub Issues and Projects for project management                                                     | TBD                                         | Thurs 9/4  |                                                                                                                             |
|                                |                                                                                                             |                                             |            |                                                                                                                             |
|                                |                                                                                                             |                                             | Tues 9/9\* |                                                                                                                             |
+--------------------------------+-------------------------------------------------------------------------------------------------------------+---------------------------------------------+------------+-----------------------------------------------------------------------------------------------------------------------------+
| Advanced Git                   | Git on the command line, advanced features and functions                                                    | TBD                                         | Thurs 9/18 |                                                                                                                             |
|                                |                                                                                                             |                                             |            |                                                                                                                             |
|                                |                                                                                                             |                                             | Tues 9/23  |                                                                                                                             |
+--------------------------------+-------------------------------------------------------------------------------------------------------------+---------------------------------------------+------------+-----------------------------------------------------------------------------------------------------------------------------+
| GitHub Actions                 | Automating tasks and workflows using GitHub Actions                                                         | TBD                                         | Thurs 10/1 |                                                                                                                             |
|                                |                                                                                                             |                                             |            |                                                                                                                             |
|                                |                                                                                                             |                                             | Tues 10/6  |                                                                                                                             |
+--------------------------------+-------------------------------------------------------------------------------------------------------------+---------------------------------------------+------------+-----------------------------------------------------------------------------------------------------------------------------+

: {tbl-colwidths="\[15,35,10,15,25\]"}

\*Note: the Tuesday 9/9 session on Project Management has been moved to 9am PT/12pm ET