---
title: "GitHub for Project Management"
---

## Aims and Objectives

Project management is a key aspect to making workflows efficient and transparent on GitHub. GitHub Projects allow teams to plan and track work in a repository and across repositories. This skills session will use directed, interactive lessons to provide NOAA Fisheries staff with a foundation in using GitHub Projects to track, plan, and manage work on GitHub.

## Prerequisites: What do I need before this workshop to follow along on my own?

1.  This stand-alone skills session is meant for those with a basic understanding of Git and GitHub. Check out our [Introduction to Git and GitHub](../intro/intro.qmd) lessons if you are new to Git and GitHub or need a refresher.
2.  Projects in GitHub rely on GitHub Issues, so you may want to refresh yourself on issues with our [Communicating in GitHub with Issues and Discussions](../issues/issues.qmd) lesson.

## Project Management in GitHub

<iframe class="slide-deck" src="../../slides/projects.html" width="900" height="600">

</iframe>