---
title: "Merge Conflits in Git and GitHub"
---

## Aims and Objectives

Merge conflicts occur when you merge branches that have competing commits. Knowing how to address merge conflicts, and how to avoid them in the first place, is a key aspect to developing your workflows in Git and GitHub. This skills session will use directed, interactive lessons to provide NOAA Fisheries staff with an understanding of why merge conflicts happen, strategies to avoid merge conflicts, and how to address them if they do occur.

## Prerequisites: What do I need before this workshop to follow along on my own?

1.  This stand-alone skills session is meant for those with a basic understanding of Git and GitHub. Check out our [Introduction to Git and GitHub](../intro/intro.qmd) lessons if you are new to Git and GitHub or need a refresher.
2.  Git workflows are based around the concept of branching. If you are not familiar with branches, be sure to take a look at our [Branches and Pull Requests](../branches/branches.qmd) lesson.

## Addressing Merge Conflicts in Git and GitHub

<iframe class="slide-deck" src="../../slides/merge-conflicts.html" width="900" height="600">

</iframe>

## Tutorial: Resolve merge conflicts with GitHub Skills